I-condition_description
B-geographic_poi
B-condition_description
I-geographic_poi
B-timeRange
I-timeRange
B-condition_temperature
I-condition_temperature
B-todo
I-todo
B-alarm_modifier
B-reminder_type
B-reference
I-reminder_type
B-timer_type
I-reference
B-negation
B-attributes
B-temperature_unit
I-alarm_modifier
